const timelineElements = [
  {
    id: 1,
    title: "Senior Full Stack Cloud Engineer",
    location: "Toronto, Canada",
    company: "Manulife",
    description: [
      "Coached multiple cohorts to upskill engineers within the organization providing mentorship and expertise surrounding cloud and software engineering principles",
      "Optimized the Manulife University Infrastructure codebase to improve maintainability and readability",
      "Implemented gitops process for kubernetes clusters to provide all applications with software infrastructure that supports non-functional requirements (e.g. istio, akv2k8s, kiali, kubecost, fluentd, newrelic, etc)",
      "Provided improved logging patterns for NEXT tool, which is an internal tool for Manulife engineers to come up with production ready scaffolding and improve the development experience",
      "Architected security patterns to enable Auth* for NEXT to implement a client only experience using Azure Entra ID as IDP which further reduces server cost",
      "Conducted code reviews for all levels of engineers on the team striving to provide constructive feedback to improve designs and code quality",
    ],
    buttonText: null,
    date: "September 2021 - Present",
    icon: "work",
    technologyUsed: [
      "NodeJS",
      "React",
      "Vite",
      "Terraform",
      "Flux (Gitops)",
      "SQL",
      "Mongodb Atlas",
      "Jenkins",
    ],
    enabled: true,
  },
  {
    id: 2,
    title: "Full Stack Engineer",
    location: "Toronto, Canada",
    company: "Manulife",
    description: [
      "Built features and microservice components of Advisor Portal using NodeJS, React and deployed to PCF (Pivotal Cloud Foundry)",
      "Implemented UI components using a custom built react SSR implementation which used AEM (Adobe Experience Manager) as the template generator and injected React components on server side",
      "Consistent branding was inherited by AEM which powered all other manulife products/client facing applications",
      "Optimized UI components (template fetches) and less dynamic data fetch functionality with a batched caching mechanism in redis",
      "Acheived load time NFR (<2s) with the optimizations to reduce time spent on network",
      "Implemented a common library of helper functions and tools (such as cache get/set, i18n lookups, auth* validations, logging patterns, etc) and published to internal artifact registry (jfrog artifactory) to improve code consistency and maintainability across all applications in insurnace",
      "Created a New Relic application monitoring dashboard from all micro services in Advisor Portal product suite",
      "Conducted code reviews of junior team members and peers",
    ],
    buttonText: "advisor.manulife.ca",
    date: "July 2019 - September 2021",
    icon: "work",
    technologyUsed: [
      "NodeJS",
      "React",
      "PCF",
      "Jenkins",
      "SQL",
      "Redis",
      "Concourse",
    ],
    enabled: true,
  },
  {
    id: 3,
    title: "Software Developer/Platform Engineer",
    location: "Toronto, Canada",
    company: "RBC",
    description: [
      "Planned and deployed an API Gateway for API Platform team using Ansible and Apigee",
      "Implemented an on-prem topology with numerous VMs to run all components of Apigee in RBC private datacenters",
      "Enabled full scalability and security of the platform during implementation and automated operation tasks using Ansible, Jenkins, Python",
      "Improved engagement turnaround time with external partners by 50%",
      "Implemented shared authorization patterns to be applied to all APIs in RBC using Oauth and Mutual Authentation (MTLS) which were used for internal and external facing APIs",
    ],
    buttonText: null,
    date: "June 2017 - July 2019",
    icon: "work",
    technologyUsed: ["Ansible", "Python", "Jenkins", "Apigee"],
    enabled: true,
  },
  {
    id: 4,
    title: "Software Engineering Student",
    location: "Waterloo, Canada",
    company: "BlackBerry",
    description: [
      "Implemented features and fixed bugs on internal Cloud Console application using Ruby on Rails",
      "First Introduction to using Microservice Arichitecture",
    ],
    buttonText: null,
    date: "September 2015 - August 2016",
    icon: "work",
    technologyUsed: ["Ruby on Rails", "MySQL"],
    enabled: false,
  },
  {
    id: 5,
    title: "B.Eng Software Engineering & Co-op",
    location: "Hamilton, Canada",
    company: "McMaster University",
    description: [],
    buttonText: null,
    date: "Class of 2017",
    icon: "school",
    technologyUsed: [],
    enabled: true,
  },
];

export default timelineElements;
